### ISSUE TITLE
MAKE ME AGARIO CLINT PLZZZZXWERKOGJI

### ISSUE THREAD

**Issue by xN3BULA** [Fan7asy/MiniDiscord#1]
PWZ FUXING MAWWNJFPODS ME A AGARIO GAMW PWS

**Comment by Fan7asy** [comment]
I will find you and I will kill you.

**Comment by xN3BULA** [comment]
Howy swhiti pwz nwo i jwust wnt agrar clint weh cn mke moneyzzzz pwzzz

**Comment by Fan7asy** [comment]
Die
